services:
  btcd:
    build: btcd
    network_mode: host
    volumes:
      - BTCWALLET:/root/.btcwallet
      - BTCD:/root/.btcd
      - ./btcd/btcd.conf:/root/.btcd/btcd.conf
      - ./btcd/btcwallet.conf:/root/.btcwallet/btcwallet.conf
      - ./btcd/server/:/app/server
    tty: true
    deploy:
      resources:
        limits:
          cpus: '8.0'   # Restrict to 8 CPU cores
        reservations:
          cpus: '8.0'

volumes:
  BTCWALLET:
  BTCD: