services:
  btcd:
    build: btcd
    network_mode: host
    volumes:
      - BTCWALLET:/root/.btcwallet
      - ./btcd/btcd.conf:/root/.btcd/btcd.conf
      - ./btcd/btcwallet.conf:/root/.btcwallet/btcwallet.conf
    tty: true

volumes:
  BTCWALLET: